# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout AP-ShipSchematics
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Build with Gradle
      run: gradle clean build --parallel
      
    - name: Stage jar for Actions
      if: ${{ github.event_name != 'release' }}
      run: mkdir staging && cp build/libs/AP-ShipSchematics.jar staging && mv staging/AP-ShipSchematics.jar staging/AP-ShipSchematics_$GITHUB_SHA.jar
    - name: Upload jar to Actions
      if: ${{ github.event_name != 'release' }}
      uses: actions/upload-artifact@v4
      with:
        name: AP-ShipSchematics_Dev-Build
        path: staging/AP-ShipSchematics_*.jar

    - name: Stage jar for Release
      if: ${{ github.event_name == 'release' }}
      run: mkdir staging && cp build/libs/AP-ShipSchematics.jar staging && mv staging/AP-ShipSchematics.jar staging/AP-ShipSchematics_${{ github.event.release.tag_name }}.jar
    - name: Upload jar to Release
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v2
      with:
       files: staging/AP-ShipSchematics_${{ github.event.release.tag_name }}.jar

